### PR TITLE
Fix error when dump and add korean app support

### PR DESCRIPTION
**Pull request by hygn**
change   
```py
dbpath = find_db('asset_a_ja_0' + source)
```
to  
```py
dbpath = find_db('asset_a_ja_0' , source)
```
and add korean app support by changing file names

### CODE REVIEW

**Comment by Francesco149** [comment]
it's better to just make the JP script check for both database filenames instead of making an entire copy with just those filenames changed

**Comment by Francesco149** [comment]
everywhere there's a _ja find_db you would do

```python
dbpath = find_db('asset_a_ja_0' , source)
if dbpath is None:
  dbpath = find_db('asset_a_ko_0' , source)
```

**Comment by hygn** [comment]
Okay I'll edit and test ASAP

**Comment by hygn** [comment]
I changed and tested it

**Comment by Francesco149** [comment]
looks good, i will clean up the commits so it's all merged into 1 or 2 commits and then merge it.

**Pull request merged**
